### ISSUE TITLE
Output Class test

### ISSUE THREAD

**Issue by STOWouters** [rubenvanassche/City-Simulator#102]

**Comment by rubenvanassche** [comment]
Scenario's
-Hele stad laten afbranden
-Brandweerkazerne in brand(moet direct geblust worden)
-5 huizen in brand steken
-2 huizen in brand steken en een winkel overvallen
-5 huizen in brand en brandweerkazerne in brand
-Brandweerkazerne laten afbranden en dan nog een huis in brand steken(er mogen geen wagens rijden)
-2 winkels overvallen
-Huis in brand steken en geen wagen laten rijden, checken of ander huis in brand schiet, en dan checken of dat ander huis dat in brand is geschoten na een tijd nog een ander huis in brand steekt.
-Winkel in brand steken en geen wagens laten rijden, checken of 2 huizen in brand schieten en daarna nog eens checken of die huizen die in brand zijn geschoten nog eens andere huizen in brand steken
-Politiekazerne laten afbranden en dan winkel laten overvalken(er mogen geen wagens rijden)
-Huis/winkel/shop/depot... in brand steken en dan testen of de repair functie goed werkt.

-Stad zonder brandweerwagens, brand laten uitbreken en er mag dan niets gebeuren
-Stad zonder politiewagens, winkel laten overvallen en er mag niets gebeuren
-Stad zonder brandweerkazernes, brand laten uitbreken en er mag niets gebeuren
-Stad zonder politiekazernes, winkel laten overvallen en er mag niet gebeuren

-Spreadfire testen in een blok met allemaal afgebrande huizen
-Spreadfire testen via een winkel in een blok met 1 huis
