### ISSUE TITLE
Creating Point Class

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#12]

**Comment by STOWouters** [comment]
@rubenvanassche : Ik heb de Point class ff moeten aanmaken, anders kon ik niets van mijn classes implementeren, die hebben allemaal een Point nodig. Maar ge moogt wel de Points testen hoor, die heb ik niet gedaan, aangezien dit eigenlijk jouw deel was :-)

**Comment by rubenvanassche** [comment]
Komt inorde ze maar heb een veel te druk weekend gehad zal er vanavond of morgen eens naar kijken. Trouwens Point bestaat toch al? Dus waar zit het probleem dan?

**Comment by STOWouters** [comment]
gaf die operator overloading bij jouw geen error? of had je dat niet geprobeerd? anyway, doe maar rustig aan hoor ;)

**Comment by rubenvanassche** [comment]
Ik heb dat even slecht getest en dat werkte helemaal maar jij hebt nog w atn aanpassingen gedaan aan het contract enzo dus misschien is daar iets misgelopen.

**Comment by STOWouters** [comment]
hmm, zou kunnen, maar ge moogt de headers ook aanpassen hoor, want sommige dingen kreeg ik niet gecompileerd omdat er een const voor/na zat, dus daar zul je ook naar moeten kijken als er iets niet werkt, ik zal de headers nog wat verder aanpassen morgen
