### ISSUE TITLE
Creating Size Class

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#13]

**Comment by STOWouters** [comment]
@rubenvanassche : De Size class is nu aangemaakt, en is terug te vinden hier, maar ik moet ze nog testen, dus fixes kunnen nog komen :)

**Comment by rubenvanassche** [comment]
Goed ben nu bezig met building en aanhangsels.

**Comment by STOWouters** [comment]
klaar! :+1:

**Comment by rubenvanassche** [comment]
Die van mij bijna ook alleen dan nog tests.
