### ISSUE TITLE
Point class problem

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#21]

**Comment by STOWouters** [comment]
en wat is het probleem?

**Comment by rubenvanassche** [comment]
Jij zei dat die toch niet werkte?

**Comment by STOWouters** [comment]
ah, die is allang solved, de points werken nu, maar ge moet nog een test schrijven hé, niet vergeten

**Comment by rubenvanassche** [comment]
Komt inorde ze vandaag werk ik alles af (:
