### ISSUE TITLE
Creating assignment and copy constructors for each class!

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#25]
The Pointer myself get's copied each time! This means that this != myself!

**Comment by STOWouters** [comment]
In de class Point vind je een voorbeeld hoe het kopiëren van objects in zijn gang gaat (getest met gtest). Ook heb ik in die test van Point (Point_test) de tests wat verder uitgebreid met DEATH tests, waar je crashes verwacht. Nu ga ik voor alle classes even die copying constructs maken als dat goed is? De test ga ik nog wat verder uitbreiden met de DEATH tests

**Comment by rubenvanassche** [comment]
Allemaal goed, ik ben er vandaag wel heel de dag niet dus veel plezier!
