### ISSUE TITLE
Almost complete rebuild of simulator

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#69]

**Comment by STOWouters** [comment]
UPDATE:

on the boterham tomorrow :smile: 
- burningDown()
- commitRob()
- robbing();
- policeTruckControl() // almost copy-paste of fireTruckControl,
- repairbuildings()
- spreadFire() @rubenvanassche ?
- step() @rubenvanassche ?

**note**
Not tested (yet), but it compiles (exclude all test-files in Eclipse)
