### ISSUE TITLE
parser should work with out not with cout

### ISSUE THREAD

**Issue by rubenvanassche** [rubenvanassche/City-Simulator#87]

**Comment by STOWouters** [comment]
hmm, in de opdracht stond volgens mij toch echt wel dat er bij een onherkenbaar element gewoon een kleine foutboodschap in de console gegeven wordt + verder gaan met parsen.. Het nut om ze te schrijven naar de out zie ik niet van in, die Out wordt toch alleen gebruikt voor tijdens de simulatie?
